### ISSUE TITLE
feat: TAP integration on paid query receipts

### ISSUE THREAD

**Issue by hopeyen** [graphprotocol/indexer-rs#1]
Receipt related operations should be dealt by an Allocation receipt manager. The original flow from indexer typescript should be replaced with TAP manager instead. 

Brief functionalities needed
- [x] [TAP](https://github.com/semiotic-ai/timeline-aggregation-protocol/) manager to handle receipts logic
  - [x] derive, cache, and look up attestation signers
    - [x] contracts - connect by network chain id
      - [x] network provider
  - [x] validate receipt format, parse receipt, validate receipt signature
  - [x] store receipt to db
- [x] receipts graphQL schema for storage and queries
- [x] extract graph-attestable from graph node response header
- [x] monitor eligible allocations for client signer
  - [x] network subgraph query for eligibility
  - [x] operator wallet -> indexer address

**Comment by aasseman** [comment]
All done!
