### ISSUE TITLE
test: simple unit tests

### ISSUE THREAD

**Issue by hopeyen** [graphprotocol/indexer-rs#14]
Task from [EPIC: Testing#7](https://github.com/graphops/indexer-service-rs/issues/7)

full coverage is the goal but be realistic about priorities 

- [x] Validate configs, fail at startup if any provided configuration isn't valid
- [x] types: Subgraph deployment id IpfsHash and bytes representations
- [ ] Create graph node instance
- [ ] Util functions
  - [ ] package_version
  - [ ] public_key
- [x] attestation_signer
routing helpers
- [ ] routes::deployment::block_numbers
- [ ] routes::basic::operator_info
