### ISSUE TITLE
EPIC: Testing

### ISSUE THREAD

**Issue by hopeyen** [graphprotocol/indexer-rs#7]
- [x] unit tests https://github.com/graphops/indexer-service-rs/issues/14
- [x] API tests https://github.com/graphops/indexer-service-rs/issues/15
  - [x] enable sqlx test in CI https://github.com/graphops/indexer-service-rs/issues/44
- [x] Integration tests https://github.com/graphops/indexer-service-rs/issues/16

Escrow subgraph deployment: `QmcPoPmisXLzsJXsdU6UUQ8Xot9ucfgaQgXvcnQDi4cUsX`, make queries to `https://api.studio.thegraph.com/proxy/53925/timeline-aggregation-protocol/v0.0.2/graphql`
