### ISSUE TITLE
EPIC: performance profiling, benchmarking

### ISSUE THREAD

**Issue by hopeyen** [graphprotocol/indexer-rs#8]
- [ ] use [flamegraphs](https://github.com/flamegraph-rs/flamegraph) to find a set of optimization targets
- [ ] create benchmarks for these optimization targets, and if appropriate use something like cachegrind and cg_diff to [measure cpu instructions](https://github.com/spacejam/sled/blob/d521c510c3b8a7e02b8602d6db6a7701b51bd33b/hack/instructions#L26), [off cpu analysis](https://www.brendangregg.com/offcpuanalysis.html)
- [ ] Track performance, and if possible diff against performance with typescript implementation
